print("Welcome to the tip calculator!")
total_bill = float(input("What was the total bill? $ "))
percentage = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
number_of_people = int(input("How many people to split the bill? "))
tip = (total_bill / number_of_people) * (percentage / 100 + 1)
print("Each person should pay: {:.2f}".format(tip))
